name: Deploy

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: rising-sector-360922

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1.1.1'

      - name: Configure Terraform
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Terraform Init
        working-directory: ../terraform
        run: terraform init

      # TODO show plan in PR comment
      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        working-directory: ../terraform
        run: terraform plan

#      - name: Terraform Apply
#        if: github.event_name == 'push'
#        working-directory: ../terraform
#        run: terraform apply --auto-approve
