name: Deploy

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get changed files in the Python folder
        id: changed-files-python
        uses: tj-actions/changed-files@v37
        with:
          files: python/**
          files_ignore: python/src/.pytest_cache/**

      - name: Get changed files in the Terraform folder
        id: changed-files-terraform
        uses: tj-actions/changed-files@v37
        with:
          files: terraform/*.{tf,tfvars}
          files_ignore: terraform/.terraform/**

      - name: Build Docker image
        if: steps.changed-files-python.outputs.any_changed == 'true'
        run: |
          echo "One or more python file(s) has changed."
          echo "List all the files that have changed: ${{ steps.changed-files-yaml.outputs.python_all_changed_files }}"

      - name: Run step if terraform file(s) change
        if: steps.changed-files-terraform.outputs.any_changed == 'true'
        run: |
          echo "One or more terraform file(s) has changed."
          echo "List all the files that have changed: ${{ steps.changed-files-yaml.outputs.terraform_all_changed_files }}"

      - name: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: rising-sector-360922

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1.1.1'

      - name: Configure Terraform
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Fmt
        working-directory: ./terraform
        run: terraform fmt -recursive

      - name: Terraform Plan
        id: terraform-plan
        if: github.event_name == 'pull_request'
        working-directory: ./terraform
        run: terraform plan -no-color

      - name: Terraform Apply
        if: github.event_name == 'push'
        working-directory: ./terraform
        run: terraform apply --auto-approve

      - uses: robburger/terraform-pr-commenter@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commenter_type: plan
          commenter_input: ${{ steps.terraform-plan.outputs.stdout }}
          commenter_exitcode: ${{ steps.terraform-plan.outputs.exitcode }}
